import { EnhancedPDFExport } from './enhanced-pdf-export';

export interface TemplateData {
  title: string;
  category: string;
  duration: string;
  difficulty: string;
  content: string;
  contentAdvice: string;
  voiceAdvice: string;
  bodyLanguageAdvice: string;
  tags?: string[];
  description?: string;
}

export class EnhancedTemplatePDFExport extends EnhancedPDFExport {
  public async generateTemplateReport(templateData: TemplateData): Promise<void> {
    try {
      // Add header with enhanced styling
      this.addHeader(
        templateData.title,
        'Professional Speech Template Guide'
      );

      // Add template info with modern cards
      this.addTemplateInfo(templateData);

      // Add main content section with enhanced formatting
      this.addContentSection(templateData);

      // Add coaching advice with modern styling
      this.addCoachingAdvice(templateData);

      // Add tags if available
      if (templateData.tags && templateData.tags.length > 0) {
        this.addTags(templateData.tags);
      }

      // Add footer
      this.addFooter('Generated by Yappyy AI Speech Coach');

    } catch (error) {
      console.error('Template PDF generation failed:', error);
      throw error;
    }
  }

  private addTemplateInfo(templateData: TemplateData): void {
    const { spacing } = this.theme;
    
    // Section header
    this.addSectionHeader('Template Information');
    
    // Create info cards in a modern grid
    const infoData = [
      {
        title: 'Category',
        value: templateData.category,
        color: this.theme.colors.primary
      },
      {
        title: 'Difficulty',
        value: templateData.difficulty,
        color: this.theme.colors.accent
      },
      {
        title: 'Duration',
        value: templateData.duration,
        color: this.theme.colors.success
      },
      {
        title: 'Type',
        value: 'Professional Template',
        color: this.theme.colors.info
      }
    ];

    // Create 2x2 grid layout
    const cardWidth = (this.pageWidth - (spacing.margin * 2) - spacing.gap) / 2;
    const cardHeight = 45;

    // First row
    this.addMetricCard(infoData[0].title, infoData[0].value, undefined, infoData[0].color);
    this.addMetricCard(infoData[1].title, infoData[1].value, undefined, infoData[1].color);
    
    this.currentY += spacing.gap;
    
    // Second row
    this.addMetricCard(infoData[2].title, infoData[2].value, undefined, infoData[2].color);
    this.addMetricCard(infoData[3].title, infoData[3].value, undefined, infoData[3].color);

    this.currentY += spacing.sectionGap;

    // Add description if available
    if (templateData.description) {
      this.addDescriptionCard(templateData.description);
    }
  }

  private addDescriptionCard(description: string): void {
    const { colors, spacing } = this.theme;
    
    this.checkPageBreak(60);
    
    // Create description card
    this.addCard('Template Overview', description, colors.secondary, '📋');
    
    this.currentY += spacing.sectionGap;
  }

  private addContentSection(templateData: TemplateData): void {
    const { colors, spacing } = this.theme;
    
    this.checkPageBreak(150);
    
    // Section header
    this.addSectionHeader('Template Content');
    
    // Content container with modern styling
    const contentWidth = this.pageWidth - (spacing.margin * 2);
    const lines = this.pdf.splitTextToSize(templateData.content, contentWidth - (spacing.padding * 2));
    const contentHeight = (lines.length * 8) + (spacing.padding * 2);
    
    // Create content card with enhanced styling
    this.createModernCard(spacing.margin, this.currentY, contentWidth, contentHeight, colors.background.accent);
    
    // Add content text with better formatting
    this.setTextStyle('body');
    this.pdf.setTextColor(colors.text.primary[0], colors.text.primary[1], colors.text.primary[2]);
    this.pdf.text(lines, spacing.margin + spacing.padding, this.currentY + spacing.padding);
    
    this.currentY += contentHeight + spacing.sectionGap;
  }

  private addCoachingAdvice(templateData: TemplateData): void {
    const { colors, spacing } = this.theme;
    
    this.checkPageBreak(150);
    
    // Section header
    this.addSectionHeader('Coaching Advice');
    
    // Add advice cards with modern styling
    this.addAdviceCard('Content Strategy', templateData.contentAdvice, colors.primary, '📝');
    this.addAdviceCard('Voice Technique', templateData.voiceAdvice, colors.success, '🎤');
    this.addAdviceCard('Body Language Tips', templateData.bodyLanguageAdvice, colors.accent, '👥');
  }

  private addAdviceCard(title: string, advice: string, color: number[], icon?: string): void {
    const { spacing } = this.theme;
    
    this.checkPageBreak(80);
    
    const cardWidth = this.pageWidth - (spacing.margin * 2);
    const lines = this.pdf.splitTextToSize(advice, cardWidth - (spacing.padding * 4));
    const cardHeight = (lines.length * 8) + (spacing.padding * 3) + 25;
    
    // Create modern card
    this.createModernCard(spacing.margin, this.currentY, cardWidth, cardHeight, color);
    
    // Title with icon
    this.setTextStyle('h4');
    this.pdf.setTextColor(color[0], color[1], color[2]);
    const titleText = icon ? `${icon} ${title}` : title;
    this.pdf.text(titleText, spacing.margin + spacing.padding, this.currentY + spacing.padding + 15);
    
    // Advice text
    this.setTextStyle('body');
    this.pdf.setTextColor(this.theme.colors.text.primary[0], this.theme.colors.text.primary[1], this.theme.colors.text.primary[2]);
    this.pdf.text(lines, spacing.margin + spacing.padding, this.currentY + spacing.padding + 30);
    
    this.currentY += cardHeight + spacing.gap;
  }

  private addTags(tags: string[]): void {
    const { colors, spacing } = this.theme;
    
    this.checkPageBreak(60);
    
    // Section header
    this.addSectionHeader('Template Tags');
    
    // Create tag chips with modern styling
    let currentX = spacing.margin;
    const maxWidth = this.pageWidth - (spacing.margin * 2);
    let currentY = this.currentY;
    
    tags.forEach((tag, index) => {
      this.setTextStyle('caption');
      const tagWidth = this.pdf.getTextWidth(tag) + (spacing.padding * 2);
      
      // Check if we need to wrap to next line
      if (currentX + tagWidth > maxWidth) {
        currentX = spacing.margin;
        currentY += 15;
        this.currentY = currentY;
      }
      
      // Create modern tag chip
      this.createTagChip(currentX, currentY - 5, tagWidth, 12, tag, colors.primary);
      
      currentX += tagWidth + 8;
    });
    
    this.currentY += 20 + spacing.sectionGap;
  }

  private createTagChip(x: number, y: number, width: number, height: number, text: string, color: number[]): void {
    const { borderRadius } = this.theme;
    
    // Tag background with subtle gradient
    this.pdf.setFillColor(color[0], color[1], color[2], 0.1);
    this.pdf.roundedRect(x, y, width, height, borderRadius.small, borderRadius.small, 'F');
    
    // Tag border
    this.pdf.setDrawColor(color[0], color[1], color[2], 0.3);
    this.pdf.setLineWidth(0.5);
    this.pdf.roundedRect(x, y, width, height, borderRadius.small, borderRadius.small, 'D');
    
    // Tag text
    this.setTextStyle('caption');
    this.pdf.setTextColor(color[0], color[1], color[2]);
    this.pdf.text(text, x + 5, y + 8);
  }
}