import { EnhancedPDFExport } from './enhanced-pdf-export';

export interface SessionData {
  id: string;
  title?: string;
  date: Date;
  duration: number;
  metrics: {
    overall: {
      score: number;
      wordCount: number;
      duration: number;
    };
    voice: {
      pace: number;
      clarity: number;
      modulation: number;
      confidence: number;
    };
    content: {
      fillerWords: string[];
      keyPhrases: string[];
      structure: number;
      clarity: number;
    };
    bodyLanguage: {
      eyeContact: number;
      posture: number;
      gestures: number;
      engagement: number;
    };
  };
  transcript: string;
  feedback: {
    strengths: string[];
    improvements: string[];
    actionItems: string[];
  };
}

export class EnhancedSessionPDFExport extends EnhancedPDFExport {
  public async generateSessionReport(session: SessionData): Promise<void> {
    try {
      // Add header with enhanced styling
      this.addHeader(
        session.title || 'Practice Session Analysis',
        `Session Report - ${new Date(session.date).toLocaleDateString('en-US', { 
          year: 'numeric', 
          month: 'long', 
          day: 'numeric' 
        })}`
      );

      // Add executive summary with modern cards
      this.addExecutiveSummary(session);

      // Add performance metrics with progress bars
      this.addPerformanceMetrics(session);

      // Add detailed analysis with enhanced styling
      this.addDetailedAnalysis(session);

      // Add transcript with better formatting
      this.addTranscript(session);

      // Add recommendations with modern styling
      this.addRecommendations(session);

      // Add footer
      this.addFooter('Generated by Yappyy AI Speech Coach');

    } catch (error) {
      console.error('Session PDF generation failed:', error);
      throw error;
    }
  }

  private addExecutiveSummary(session: SessionData): void {
    const { spacing } = this.theme;
    
    // Section header
    this.addSectionHeader('Executive Summary');
    
    // Add summary cards in a modern grid layout
    const summaryData = [
      {
        title: 'Overall Score',
        value: `${Math.round(session.metrics.overall.score)}%`,
        subtitle: 'Performance Rating',
        color: this.theme.colors.primary
      },
      {
        title: 'Speaking Rate',
        value: `${session.metrics.voice.pace} WPM`,
        subtitle: 'Words per minute',
        color: this.theme.colors.success
      },
      {
        title: 'Duration',
        value: `${Math.floor(session.duration / 60)}:${String(session.duration % 60).padStart(2, '0')}`,
        subtitle: 'Session length',
        color: this.theme.colors.accent
      },
      {
        title: 'Word Count',
        value: session.metrics.overall.wordCount.toString(),
        subtitle: 'Total words spoken',
        color: this.theme.colors.info
      }
    ];

    // Create 2x2 grid layout
    const cardWidth = (this.pageWidth - (spacing.margin * 2) - spacing.gap) / 2;
    const cardHeight = 50;

    // First row
    this.addMetricCard(summaryData[0].title, summaryData[0].value, summaryData[0].subtitle, summaryData[0].color);
    this.addMetricCard(summaryData[1].title, summaryData[1].value, summaryData[1].subtitle, summaryData[1].color);
    
    this.currentY += spacing.gap;
    
    // Second row
    this.addMetricCard(summaryData[2].title, summaryData[2].value, summaryData[2].subtitle, summaryData[2].color);
    this.addMetricCard(summaryData[3].title, summaryData[3].value, summaryData[3].subtitle, summaryData[3].color);

    this.currentY += spacing.sectionGap;
  }

  private addPerformanceMetrics(session: SessionData): void {
    const { colors, spacing } = this.theme;
    
    this.checkPageBreak(200);
    
    // Section header
    this.addSectionHeader('Performance Metrics');
    
    // Voice Quality Section
    this.addSubsectionHeader('Voice Quality', colors.primary);
    this.addProgressBar('Clarity', session.metrics.voice.clarity, 100, colors.primary);
    this.addProgressBar('Modulation', session.metrics.voice.modulation, 100, colors.secondary);
    this.addProgressBar('Confidence', session.metrics.voice.confidence, 100, colors.accent);
    
    this.currentY += spacing.gap;
    
    // Body Language Section
    this.addSubsectionHeader('Body Language', colors.success);
    this.addProgressBar('Eye Contact', session.metrics.bodyLanguage.eyeContact, 100, colors.success);
    this.addProgressBar('Posture', session.metrics.bodyLanguage.posture, 100, colors.success);
    this.addProgressBar('Engagement', session.metrics.bodyLanguage.engagement, 100, colors.success);
    
    this.currentY += spacing.gap;
    
    // Content Analysis Section
    this.addSubsectionHeader('Content Analysis', colors.info);
    this.addProgressBar('Structure', session.metrics.content.structure, 100, colors.info);
    this.addProgressBar('Clarity', session.metrics.content.clarity, 100, colors.info);
    
    // Filler Words Count
    this.setTextStyle('body');
    this.pdf.setTextColor(colors.text.primary[0], colors.text.primary[1], colors.text.primary[2]);
    this.pdf.text(`Filler Words Detected: ${session.metrics.content.fillerWords.length}`, spacing.margin, this.currentY);
    this.currentY += 15;
    
    if (session.metrics.content.fillerWords.length > 0) {
      this.setTextStyle('caption');
      this.pdf.setTextColor(colors.text.secondary[0], colors.text.secondary[1], colors.text.secondary[2]);
      this.pdf.text(`Most common: ${session.metrics.content.fillerWords.slice(0, 3).join(', ')}`, spacing.margin, this.currentY);
      this.currentY += 10;
    }
    
    this.currentY += spacing.sectionGap;
  }

  private addSubsectionHeader(title: string, color: number[]): void {
    const { spacing } = this.theme;
    
    this.setTextStyle('h4');
    this.pdf.setTextColor(color[0], color[1], color[2]);
    this.pdf.text(title, spacing.margin, this.currentY);
    this.currentY += 15;
  }

  private addDetailedAnalysis(session: SessionData): void {
    const { colors, spacing } = this.theme;
    
    this.checkPageBreak(150);
    
    // Section header
    this.addSectionHeader('Detailed Analysis');
    
    // Strengths
    this.addAnalysisCard('Key Strengths', session.feedback.strengths, colors.success, '🌟');

    // Areas for Improvement
    this.addAnalysisCard('Areas for Improvement', session.feedback.improvements, colors.warning, '📈');

    // Action Items
    this.addAnalysisCard('Recommended Actions', session.feedback.actionItems, colors.primary, '✅');
  }

  private addAnalysisCard(title: string, items: string[], color: number[], icon?: string): void {
    const { spacing } = this.theme;
    
    this.checkPageBreak(80);
    
    const cardWidth = this.pageWidth - (spacing.margin * 2);
    const itemHeight = 20;
    const cardHeight = (items.length * itemHeight) + (spacing.padding * 3) + 25;
    
    // Create modern card
    this.createModernCard(spacing.margin, this.currentY, cardWidth, cardHeight, color);
    
    // Title with icon
    this.setTextStyle('h4');
    this.pdf.setTextColor(color[0], color[1], color[2]);
    const titleText = icon ? `${icon} ${title}` : title;
    this.pdf.text(titleText, spacing.margin + spacing.padding, this.currentY + spacing.padding + 15);
    
    // Items with bullet points
    this.setTextStyle('body');
    items.forEach((item, index) => {
      const y = this.currentY + spacing.padding + 35 + (index * itemHeight);
      
      // Bullet point
      this.pdf.setFillColor(color[0], color[1], color[2]);
      this.pdf.circle(spacing.margin + (spacing.padding * 2), y - 2, 1.5, 'F');
      
      // Item text
      this.pdf.setTextColor(this.theme.colors.text.primary[0], this.theme.colors.text.primary[1], this.theme.colors.text.primary[2]);
      const lines = this.pdf.splitTextToSize(item, cardWidth - (spacing.padding * 6));
      this.pdf.text(lines, spacing.margin + (spacing.padding * 4), y);
      
      // Adjust height if text wraps
      if (lines.length > 1) {
        this.currentY += (lines.length - 1) * 8;
      }
    });
    
    this.currentY += cardHeight + spacing.gap;
  }

  private addTranscript(session: SessionData): void {
    const { colors, spacing } = this.theme;
    
    this.checkPageBreak(120);
    
    // Add new page for transcript
    this.pdf.addPage();
    this.currentY = spacing.margin;
    
    // Section header
    this.addSectionHeader('Session Transcript');
    
    // Transcript container with modern styling
    const transcriptWidth = this.pageWidth - (spacing.margin * 2);
    const lines = this.pdf.splitTextToSize(session.transcript, transcriptWidth - (spacing.padding * 2));
    const transcriptHeight = (lines.length * 8) + (spacing.padding * 2);
    
    // Create transcript card
    this.createModernCard(spacing.margin, this.currentY, transcriptWidth, transcriptHeight, colors.background.accent);
    
    // Add transcript text with better formatting
    this.setTextStyle('body');
    this.pdf.setTextColor(colors.text.primary[0], colors.text.primary[1], colors.text.primary[2]);
    this.pdf.text(lines, spacing.margin + spacing.padding, this.currentY + spacing.padding);
    
    this.currentY += transcriptHeight + spacing.sectionGap;
  }

  private addRecommendations(session: SessionData): void {
    const { colors, spacing } = this.theme;
    
    this.checkPageBreak(120);
    
    // Section header
    this.addSectionHeader('Action Plan & Recommendations');
    
    // Add action items in a modern numbered format
    session.feedback.actionItems.forEach((item, index) => {
      this.addActionItem(item, index + 1);
    });
  }

  private addActionItem(item: string, number: number): void {
    const { colors, spacing } = this.theme;
    
    this.checkPageBreak(50);
    
    const itemWidth = this.pageWidth - (spacing.margin * 2);
    const itemHeight = 40;
    
    // Create action item card
    this.createModernCard(spacing.margin, this.currentY, itemWidth, itemHeight, colors.primary);
    
    // Number circle with modern styling
    this.pdf.setFillColor(colors.primary[0], colors.primary[1], colors.primary[2]);
    this.pdf.circle(spacing.margin + 15, this.currentY + 20, 10, 'F');
    
    // Number text
    this.setTextStyle('h4');
    this.pdf.setTextColor(255, 255, 255);
    const numberWidth = this.pdf.getTextWidth(number.toString());
    this.pdf.text(
      number.toString(),
      spacing.margin + 15 - (numberWidth / 2),
      this.currentY + 23
    );
    
    // Item text
    this.setTextStyle('body');
    this.pdf.setTextColor(colors.text.primary[0], colors.text.primary[1], colors.text.primary[2]);
    const lines = this.pdf.splitTextToSize(item, itemWidth - 50);
    this.pdf.text(lines, spacing.margin + 35, this.currentY + 20);
    
    this.currentY += itemHeight + spacing.gap;
  }
}