import { jsPDF } from 'jspdf';

export interface SimpleTemplateData {
  content: string;
}

function ensureArial(pdf: jsPDF) {
  try {
    // Use Arial as primary font
    pdf.setFont('Arial', 'normal');
  } catch {
    // Fallback to Helvetica if Arial not available
    pdf.setFont('helvetica', 'normal');
  }
}

export async function generatePlainTemplatePDF(templateData: SimpleTemplateData, filename: string = 'template.pdf') {
  try {
    const pdf = new jsPDF('p', 'mm', 'a4');
    // Fonts should never throw; default to Helvetica
    try { ensureArial(pdf); } catch { pdf.setFont('helvetica', 'normal'); }
    pdf.setFontSize(12);

    const margin = 15;
    const pageWidth = pdf.internal.pageSize.getWidth();
    const usableWidth = pageWidth - margin * 2;
    const startY = 20;

    const text = String(templateData?.content ?? '').trim() || ' ';
    const lines = pdf.splitTextToSize(text, usableWidth);
    pdf.text(lines, margin, startY);

    // Append footer line: "generated by yappyy" using Arial (fallback to Helvetica)
    let endY = startY + lines.length * 6 + 10;
    const pageHeight = pdf.internal.pageSize.getHeight();
    if (endY > pageHeight - margin) {
      pdf.addPage();
      endY = margin;
    }
    try {
      // Use Arial for footer
      pdf.setFont('Arial', 'normal');
    } catch {
      pdf.setFont('helvetica', 'normal');
    }
    pdf.setFontSize(10);
    pdf.text('generated by yappyy', margin, endY);

    // Robust save: try jsPDF save, then anchor fallback
    try {
      pdf.save(filename);
    } catch (e) {
      const blob = pdf.output('blob');
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(() => URL.revokeObjectURL(url), 0);
    }
  } catch (err) {
    // Bubble up to caller; they have a fallback chain
    console.error('Simple PDF export error:', err);
    throw err;
  }
}

export default generatePlainTemplatePDF;


