import { jsPDF } from 'jspdf';

export interface SimpleTemplateData {
  content: string;
}

function ensurePoppins(pdf: jsPDF) {
  try {
    const fontName = 'Poppins';
    // @ts-ignore
    const w: any = typeof window !== 'undefined' ? window : {};
    if (w.__POPPINS_TTF__) {
      // @ts-ignore
      pdf.addFileToVFS('Poppins-Regular.ttf', w.__POPPINS_TTF__);
      // @ts-ignore
      pdf.addFont('Poppins-Regular.ttf', fontName, 'normal');
      pdf.setFont(fontName, 'normal');
      return;
    }
    pdf.setFont('Poppins', 'normal');
  } catch {
    // Fallback if Poppins not available
    pdf.setFont('helvetica', 'normal');
  }
}

export async function generatePlainTemplatePDF(templateData: SimpleTemplateData, filename: string = 'template.pdf') {
  const pdf = new jsPDF('p', 'mm', 'a4');
  ensurePoppins(pdf);
  pdf.setFontSize(12);

  const margin = 15;
  const pageWidth = pdf.internal.pageSize.getWidth();
  const usableWidth = pageWidth - margin * 2;
  const startY = 20;

  const text = (templateData.content || '').trim() || ' ';
  const lines = pdf.splitTextToSize(text, usableWidth);
  pdf.text(lines, margin, startY);

  // Append footer line: "generated by yappyy" using Arial (fallback to Helvetica)
  let endY = startY + lines.length * 6 + 10;
  const pageHeight = pdf.internal.pageSize.getHeight();
  if (endY > pageHeight - margin) {
    pdf.addPage();
    endY = margin;
  }
  try {
    // Arial is not a built-in jsPDF font; attempt and fall back to Helvetica
    // @ts-ignore
    pdf.setFont('arial', 'normal');
  } catch {
    pdf.setFont('helvetica', 'normal');
  }
  pdf.setFontSize(10);
  pdf.text('generated by yappyy', margin, endY);

  pdf.save(filename);
}

export default generatePlainTemplatePDF;


