// Simplified Yappyy Template PDF Export with Clean Design
import { jsPDF } from 'jspdf';

export interface TemplateData {
  title: string;
  category: string;
  duration: string;
  difficulty: string;
  content: string;
  contentAdvice: string;
  voiceAdvice: string;
  bodyLanguageAdvice: string;
  tags?: string[];
  description?: string;
}

export class TemplatePDFExportService {
  private pdf: jsPDF;
  private pageHeight: number = 297; // A4 height in mm
  private pageWidth: number = 210; // A4 width in mm
  private margin: number = 20;
  private currentY: number = 20;

  // Simplified Yappyy color scheme
  private colors = {
    primary: [37, 99, 235], // Blue-600 - main Yappyy color
    secondary: [59, 130, 246], // Blue-500 
    accent: [99, 102, 241], // Indigo-500
    text: [15, 23, 42], // Dark text
    textLight: [71, 85, 105], // Gray text
    textMuted: [148, 163, 184], // Light gray text
    white: [255, 255, 255],
    gray: [248, 250, 252], // Light background
    success: [34, 197, 94], // Green
    warning: [251, 146, 60], // Orange
  };

  constructor() {
    this.pdf = new jsPDF('p', 'mm', 'a4');
    this.setupStyling();
  }

  private setupStyling(): void {
    this.pdf.setFont('Arial', 'normal');
    this.pdf.setFontSize(10);
    this.pdf.setTextColor(this.colors.text[0], this.colors.text[1], this.colors.text[2]);
  }

  public async generateTemplateReport(templateData: TemplateData): Promise<void> {
    try {
      this.currentY = this.margin;
      
      // Clean header
      this.addCleanHeader(templateData.title);
      
      // Template info cards
      this.addTemplateCards(templateData);
      
      // Content section
      this.addContentSection(templateData);
      
      // Coaching advice
      this.addCoachingSection(templateData);
      
      // Footer
      this.addFooter();
      
    } catch (error) {
      console.error('PDF generation failed:', error);
      throw error;
    }
  }

  private addCleanHeader(title: string): void {
    // Simple title only
    this.pdf.setFontSize(16);
    this.pdf.setFont('Arial', 'bold');
    this.pdf.setTextColor(0, 0, 0);
    this.pdf.text(title, this.margin, this.currentY);
    this.currentY += 15;
  }

  private addTemplateCards(templateData: TemplateData): void {
    // Simple text information
    this.pdf.setFontSize(12);
    this.pdf.setFont('Arial', 'normal');
    this.pdf.setTextColor(0, 0, 0);
    
    this.pdf.text(`Category: ${templateData.category}`, this.margin, this.currentY);
    this.currentY += 8;
    this.pdf.text(`Difficulty: ${templateData.difficulty}`, this.margin, this.currentY);
    this.currentY += 8;
    this.pdf.text(`Duration: ${templateData.duration}`, this.margin, this.currentY);
    this.currentY += 8;
    
    if (templateData.description) {
      this.pdf.text(`Description: ${templateData.description}`, this.margin, this.currentY);
      this.currentY += 8;
    }
    
    this.currentY += 10;
  }

  // Removed info card method - using simple text instead

  private addContentSection(templateData: TemplateData): void {
    // Section title
    this.pdf.setFontSize(14);
    this.pdf.setFont('Arial', 'bold');
    this.pdf.setTextColor(0, 0, 0);
    this.pdf.text('Template Content', this.margin, this.currentY);
    this.currentY += 15;
    
    // Content text
    this.pdf.setFontSize(11);
    this.pdf.setFont('Arial', 'normal');
    this.pdf.setTextColor(0, 0, 0);
    
    const lines = this.pdf.splitTextToSize(templateData.content, this.pageWidth - this.margin * 2);
    this.pdf.text(lines, this.margin, this.currentY);
    
    this.currentY += lines.length * 5 + 15;
  }

  private addCoachingSection(templateData: TemplateData): void {
    // Section title
    this.pdf.setFontSize(14);
    this.pdf.setFont('Arial', 'bold');
    this.pdf.setTextColor(0, 0, 0);
    this.pdf.text('Coaching Advice', this.margin, this.currentY);
    this.currentY += 15;
    
    // Content advice
    this.addAdviceText('Content', templateData.contentAdvice);
    
    // Voice advice
    this.addAdviceText('Voice', templateData.voiceAdvice);
    
    // Body language advice
    this.addAdviceText('Body Language', templateData.bodyLanguageAdvice);
  }

  private addAdviceText(label: string, advice: string): void {
    // Label
    this.pdf.setFontSize(12);
    this.pdf.setFont('Arial', 'bold');
    this.pdf.setTextColor(0, 0, 0);
    this.pdf.text(`${label}:`, this.margin, this.currentY);
    this.currentY += 8;
    
    // Advice text
    this.pdf.setFontSize(11);
    this.pdf.setFont('Arial', 'normal');
    const lines = this.pdf.splitTextToSize(advice, this.pageWidth - this.margin * 2);
    this.pdf.text(lines, this.margin, this.currentY);
    
    this.currentY += lines.length * 5 + 10;
  }

  private addFooter(): void {
    // Simple footer text only
    this.pdf.setFontSize(9);
    this.pdf.setFont('Arial', 'normal');
    this.pdf.setTextColor(0, 0, 0);
    this.pdf.text('Generated by Yappyy', this.margin, this.pageHeight - 20);
    
    const date = new Date().toLocaleDateString();
    const dateWidth = this.pdf.getTextWidth(date);
    this.pdf.text(date, this.pageWidth - this.margin - dateWidth, this.pageHeight - 20);
  }

  public async downloadPDF(filename: string): Promise<void> {
    this.pdf.save(filename);
  }
}